### ISSUE TITLE
Will this work with Amazon RDS?

### ISSUE THREAD

**Issue by atlithorn** [realm-demos/realm-dvdrental#1]
I ask because AFAIK the only logical decoding output plugin available for PostgreSQL on Amazon RDS is `test_decoding` but I don't see any mention of plugin installation in your README.

**Comment by atlithorn** [comment]
(Congrats on this achievement by the way, this is what we've been waiting for)

**Comment by bigfish24** [comment]
First thanks! Yes, this will work with Amazon RDS. We use the default `test_decoding` plugin to read the output. We originally built it using our own plugin that produced `json` vs. the text based output of `test_decoding` but we switched specifically for this purpose. The benefit of `test_decoding` is that it requires no installation and we noticed was already available on RDS.

**Comment by atlithorn** [comment]
Impressive. Thanks for the response.

**Comment by bigfish24** [comment]
Thanks again, feel free to reach out to me directly at af@realm.io or sales@realm.io if you want to try the demo.
